# Generated by Django 3.2.13 on 2022-11-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('profileBio', models.CharField(max_length=500)),
                ('zipcode', models.CharField(max_length=15)),
                ('skills', models.CharField(max_length=200)),
                ('githubUser', models.CharField(max_length=15)),
                ('yearsExp', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
