# Generated by Django 3.2.13 on 2022-12-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_signin_remove_candidateprofile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionTitle', models.CharField(max_length=75)),
                ('jobType', models.CharField(max_length=75)),
                ('cityLocation', models.CharField(max_length=30)),
                ('stateLocation', models.CharField(max_length=30)),
                ('preferredSkills', models.CharField(max_length=50)),
                ('jobDescription', models.CharField(max_length=1000)),
                ('expirationDate', models.DateField(max_length=30)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
