# Generated by Django 3.2.13 on 2022-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_jobpost_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='preferredSkills',
            field=models.TextField(max_length=50),
        ),
    ]
