# Generated by Django 3.2.13 on 2022-12-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('profileBio', models.CharField(max_length=500)),
                ('zipcode', models.CharField(max_length=15)),
                ('skills', models.CharField(max_length=200)),
                ('githubUser', models.CharField(max_length=15)),
                ('yearsExp', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=75)),
                ('lname', models.CharField(max_length=75)),
                ('company', models.CharField(max_length=500)),
                ('zipcode', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='signIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionTitle', models.CharField(max_length=75)),
                ('jobType', models.IntegerField(choices=[(0, 'Full Time'), (1, 'Part Time')])),
                ('cityLocation', models.CharField(max_length=30)),
                ('stateLocation', models.CharField(max_length=30)),
                ('preferredSkills', models.TextField()),
                ('jobDescription', models.TextField()),
                ('company', models.CharField(default='a', max_length=75)),
                ('expirationDate', models.DateField(max_length=30)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('numInterestCands', models.IntegerField(default=0)),
                ('interestedCands', models.ManyToManyField(default=None, related_name='job_Posts', to='polls.CandidateProfile')),
                ('recruiter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='polls.recruiterprofile')),
            ],
        ),
    ]
