# Generated by Django 4.1.2 on 2022-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='compScore',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='stateLocation',
            field=models.CharField(max_length=2),
        ),
    ]
