# Generated by Django 3.2.13 on 2022-12-07 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_jobpost_compscore_alter_jobpost_statelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='polls.candidateprofile')),
                ('jobPost', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='polls.jobpost')),
            ],
        ),
    ]
